complete -c zua -n '__fish_use_subcommand' -f -a add -d 'Adds the provided path to the data file'
complete -c zua -n '__fish_use_subcommand' -f -a clean -d 'Removes any invalid paths from the data file'
complete -c zua -n '__fish_use_subcommand' -f -a edit -d 'Open up the data file in $EDITOR.'
complete -c zua -n '__fish_use_subcommand' -f -a init -d 'Outputs the required shell code to be added to shell config'
complete -c zua -n '__fish_use_subcommand' -f -a completion -d 'Outputs completion for options.'

complete -c zua -l help -s h -d "Print usage"
complete -c zua -l version -s v -d "Print version"
complete -c zua -l patternmatch -s p -d "Enable lua pattern matching"
complete -c zua -l case -s c -d "Make the pattern case sensitive"
complete -c zua -l name -s n -r -d "Set the name of the command generated by init. ('cd' not supported)"
complete -c zua -l nojump -s N -d "Avoid generating the 'zua' function in the shell. Useful if you only want the path adding alongside your own picker."
